# -*- coding: utf-8 -*-
"""sk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XUmrSORzq7E8Dtj5CRk3gKzSp3Q5wglZ
"""
# https://github.com/tjmoon0104/pytorch-tiny-imagenet/blob/master/AlexNet.ipynb
from ast import Index
import numpy as np
from scipy import stats
import torch
from torch.optim.lr_scheduler import LambdaLR
import math
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data.sampler import SubsetRandomSampler
import torchvision
import torchvision.transforms as transforms
import os
import pandas as pd
from tqdm import tqdm
import copy
import torch.utils.data as data
import torchvision.datasets as datasets
from torch.utils.data import Dataset
import time
from pathlib import Path
# from livelossplot import PlotLosses
import torchvision.models as models
import torch
# from neurodl.targeted_neurogenesis import targeted_neurogenesis

import argparse
device = torch.device("cuda:1" if torch.cuda.is_available() else "cpu")


class AlexNet(nn.Module):

  def __init__(self, num_classes=100,tiny_imagenet=False):
    super(AlexNet, self).__init__()
    if tiny_imagenet:
        self.features = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(64, 192, kernel_size=5, padding=2),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
            nn.Conv2d(192, 384, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(384, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, padding=1),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(kernel_size=3, stride=2),
        )
        self.classifier = nn.Sequential(
#             nn.Dropout(),
            nn.Linear(256 * 6 * 6, 4096),
            nn.ReLU(inplace=True),
#             nn.Dropout(),
            nn.Linear(4096, 4096),
            nn.ReLU(inplace=True),
            nn.Linear(4096, num_classes),
        )
    else:
        self.features = nn.Sequential(
          nn.Conv2d(3, 64, kernel_size=3, stride=2, padding=1),
          nn.ReLU(inplace=True),
          nn.MaxPool2d(kernel_size=3, stride=2),
          nn.Conv2d(64, 192, kernel_size=3, stride=1, padding=1),
          nn.ReLU(inplace=True),
          nn.MaxPool2d(kernel_size=3, stride=2),
          nn.Conv2d(192, 384, kernel_size=3, stride=1, padding=1),
          nn.ReLU(inplace=True),
          nn.Conv2d(384, 256, kernel_size=3, stride=1, padding=1),
          nn.ReLU(inplace=True),
          nn.Conv2d(256, 256, kernel_size=3, stride=1, padding=1),
          nn.ReLU(inplace=True),
          nn.MaxPool2d(kernel_size=3, stride=2),
        )
    self.classifier = nn.Sequential(
      nn.Dropout(),
      nn.Linear(256 * 1 * 1, 4096),
      nn.ReLU(inplace=True),
      nn.Dropout(),
      nn.Linear(4096, 4096),
      nn.ReLU(inplace=True),
      nn.Linear(4096, num_classes),
    )
    
    self.fc1 = nn.Linear(256 * 1 * 1, 4096)
    self.fc2 = nn.Linear(4096, 4096)
    self.fc3 = nn.Linear(4096, num_classes)
    
    
    self.input_img = None
    self.after_flatten = None
    self.before_relu_fc1 = None
    self.after_relu_fc1 = None
    self.before_relu_fc2 = None
    self.after_relu_fc2 = None
    self.before_relu_fc3 = None
    self.after_relu_fc3 = None

  def forward(self, x):
    self.input_img = x.clone().detach()
    x = self.features(x)
#     print(f'before flatten {x.shape}')
    x = torch.flatten(x, 1)
    #x = self.classifier(x)
#     print(f'after flatten {x.shape}')
    self.after_flatten = x.clone().detach()
    x = self.fc1(x)
    self.before_relu_fc1 = x.clone().detach()
    x = F.relu(x)
    self.after_relu_fc1 = x.clone().detach()
    
    x = self.fc2(x)
    self.before_relu_fc2 = x.clone().detach()
    x = F.relu(x)
    self.after_relu_fc2 = x.clone().detach()
    
    x = self.fc3(x)
    self.before_relu_fc3 = x.clone().detach()
    #x = F.relu(x)
    #self.after_relu_fc3 = x.clone().detach()
    
    return x

  def get_intermediate_states(self):
    return [
    self.input_img,
    self.after_flatten,
    self.after_relu_fc1,
    self.after_relu_fc2,
    self.before_relu_fc3    
    ]



def alexnet(pretrained=False, **kwargs):
    r"""AlexNet model architecture from the
    `"One weird trick..." <https://arxiv.org/abs/1404.5997>`_ paper.
    Args:
        pretrained (bool): If True, returns a model pre-trained on ImageNet
    """
    model = AlexNet(**kwargs)
    if pretrained:
        model.load_state_dict(model_zoo.load_url(model_urls["alexnet"]))
#     
    #wodrop
    model.classifier[0] = nn.Linear(256 * 1 * 1, 4096)
    model.classifier[4] = nn.Linear(4096, 200)
    #wdrop
#     model.classifier[1] = nn.Linear(256 * 1 * 1, 4096)
#     model.classifier[6] = nn.Linear(4096, 200)

    return model

class TinyImagenetCorrupted(Dataset):
    def __init__(self, root="tiny-imagenet-200", split='train', corrupt_prob=0.0, transform=None):
        """
        Args:
            root (str): Root directory of the Tiny-ImageNet dataset.
            split (str): Dataset split, one of ['train', 'val', 'test'].
            corrupt_prob (float): Probability of corrupting a label.
            transform (callable, optional): Optional transform to be applied on a sample.
        """
        self.root = os.path.join(root, split)
        self.dataset = datasets.ImageFolder(self.root, transform=transform)
        self.targets = np.array([label for _, label in self.dataset.samples])
        self.corrupt_prob = corrupt_prob
        self.n_classes = len(self.dataset.classes)

        # Store original and corrupted targets
        self.original_targets = copy.deepcopy(self.targets)
        self.corrupted_targets = copy.deepcopy(self.targets)

        # Corrupt the labels if corrupt_prob > 0
        if corrupt_prob > 0:
            self._corrupt_labels()

    def _corrupt_labels(self):
        """
        Corrupt labels with a probability defined by corrupt_prob.
        """
        np.random.seed(42)  # Ensure reproducibility
        mask = np.random.rand(len(self.targets)) < self.corrupt_prob
        corrupt_labels = np.random.choice(self.n_classes, size=mask.sum(), replace=True)
        self.corrupted_targets[mask] = corrupt_labels

    def __getitem__(self, index):
        """
        Args:
            index (int): Index
        Returns:
            tuple: (image, target) where target is the possibly corrupted label.
        """
        path, _ = self.dataset.samples[index]
        image = self.dataset.loader(path)
        if self.dataset.transform is not None:
            image = self.dataset.transform(image)
        label = self.corrupted_targets[index]
        return image, label

    def __len__(self):
        return len(self.dataset.samples)

    def get_targets(self):
        """
        Returns:
            tuple: (original_targets, corrupted_targets)
        """
        return self.corrupt_prob, self.original_targets, self.corrupted_targets


def get_cifar_dataloaders_corrupted(corrupt_prob=0, batch_size=50,fashion=False,cifar10=False,mnist=False,tiny_imagenet=False):
    transform = transforms.Compose(
        [transforms.ToTensor(),
         transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

    if fashion:
        transform = transforms.Compose(
        [transforms.ToTensor(),
         transforms.Normalize((0.5,), (0.5,))])
        trainset = FashionMNISTCorrupted(root='./data', train=True, download=True, transform=transform,
                                    corrupt_prob=corrupt_prob)
        
        testset = FashionMNISTCorrupted(root='./data', train=False, download=True, transform=transform,
                                   corrupt_prob=corrupt_prob)  
    elif cifar10:
        trainset = CIFAR10Corrupted(root='./data', train=True, download=True, transform=transform,
                                    corrupt_prob=corrupt_prob)
        testset = CIFAR10Corrupted(root='./data', train=False, download=True, transform=transform,
                                   corrupt_prob=corrupt_prob)
    elif tiny_imagenet:
        # Use TinyImagenetCorrupted class for Tiny-ImageNet with the given corruption probability
        transform = transforms.Compose(
            [transforms.ToTensor()]
        )
        trainset = TinyImagenetCorrupted(root='../data/tiny-imagenet-200', split='train', corrupt_prob=corrupt_prob, transform=transform)
        testset = TinyImagenetCorrupted(root='../data/tiny-imagenet-200', split='val', corrupt_prob=0.0, transform=transform)  # Validation set as test

        
    elif mnist:
        transform = transforms.Compose(
        [transforms.ToTensor(),
         transforms.Normalize((0.5,), (0.5,))])
        trainset = MNISTCorrupted(root='./data', train=True, download=True, transform=transform,
                                    corrupt_prob=corrupt_prob)
        testset = MNISTCorrupted(root='./data', train=False, download=True, transform=transform,
                                   corrupt_prob=corrupt_prob)
    else:
        trainset = CIFAR100Corrupted(root='./data', train=True, download=True, transform=transform,
                                    corrupt_prob=corrupt_prob)
        testset = CIFAR100Corrupted(root='./data', train=False, download=True, transform=transform,
                                   corrupt_prob=corrupt_prob)
    og_prob, og_targets, cor_targets = trainset.get_targets()
    train_loader = torch.utils.data.DataLoader(trainset, batch_size=batch_size, shuffle=True)
    test_loader = torch.utils.data.DataLoader(testset, batch_size=batch_size, shuffle=True)
    return train_loader, test_loader, og_prob, og_targets, cor_targets







"""**Training loop**"""
if __name__ == "__main__":

    torch.manual_seed(42)
    batch_size = 500
    
    parser = argparse.ArgumentParser(description="Select run and corruption.")
    runs = [1,2,3]
    corrution_prob = [0.0,0.2,0.4,0.6,0.8,1.0]
    parser.add_argument(
        "-run", type=int, required=True, choices=runs, help="select run"
    )

    parser.add_argument(
        "-corr", type=float, required=True, choices=corrution_prob, help="select corruption"
    )

    args = parser.parse_args()
    
    # Access arguments
    run = args.run
    corrupt = args.corr
    
    if run not in runs:
        args.print_help()
    if corrupt not in corrution_prob:
        args.print_help()

    _, test_loader , _, _, _ = get_cifar_dataloaders_corrupted(batch_size=batch_size,tiny_imagenet=True)

    path = '/mnt/NVME2TB/simran/PCA/TinyImagenet_Alexnet'
    os.makedirs(path,exist_ok=True)
    network_path = os.path.join(path,'Network')
    os.makedirs(network_path, exist_ok=True)
    res_path = os.path.join(path,'Accuracy_results')
#     for corrupt in corrution_prob:
    
    print(f'corrupt: {corrupt}')
    cur_network_dir = os.path.join(network_path, str(corrupt))
    # temp2 = os.path.join(cur_dir, 'Accuracy_results')
    os.makedirs(cur_network_dir, exist_ok=True)

    corrupted_train, _ , prob, og_targets, cor_targets = get_cifar_dataloaders_corrupted(corrupt, batch_size=batch_size,tiny_imagenet=True)

    if prob == corrupt:
        mask = og_targets == cor_targets
        temp_count = np.sum(mask)
        percent = (temp_count/len(mask))*100
        percent = round(percent,2)
        label_data = {
            'True Label': og_targets,
            'Corrupted Label': cor_targets,
        }
        label_csv = pd.DataFrame(data=label_data)
        label_csv.to_csv(os.path.join(cur_network_dir,f'label_info_corruption_{corrupt}_percent_{percent}.csv'))
#         for run in runs:
    
    print(f'run: {run}')
    run_path = os.path.join(cur_network_dir,f'Run_{run}')
    os.makedirs(run_path,exist_ok=True)

    results = {
      'epoch': [],
      'Train_accuracy': [],
      'Test_accuracy': [],
    }

    model = AlexNet(num_classes=200, tiny_imagenet=True)
    loss_func=nn.CrossEntropyLoss().to(device)
    optimizer=optim.Adam(model.parameters(),betas=(0.9, 0.999),lr = 0.0001)
    model.to(device)
    model.train()
    torch.save(model.state_dict(),os.path.join(run_path,'./initialized_model.pth'))
    epoches = 500
    for epoch in range(epoches):
        train_loss = 0
        test_loss = 0
        train_acc = 0
        test_acc = 0
        temp_acc = 0
        count = 0

        for idx, (inputs, labels) in tqdm(enumerate(corrupted_train), total=len(corrupted_train), desc="Mini Batches"):
            inputs, labels = inputs.to(device), labels.to(device)
            model.zero_grad()
            output = model(inputs)
            loss = loss_func(output, labels.type(torch.int64))
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
#             _, temp_pred = torch.max(output, 1)
#             temp_acc += torch.sum(temp_pred == labels.data).item()
            count += len(labels)

            temp_acc += (torch.argmax(output, 1) == labels).float().sum().item()
        train_acc = (temp_acc/count) * 100

        print(f'\n Corrupt: {corrupt}, Run: {run} Epoch: {epoch} Training accuracy:{train_acc}, correct: {temp_acc}, total:{count}')
        results['Train_accuracy'].append(train_acc)
        results['epoch'].append(epoch+1)

        acc = 0
        test_count = 0
        total_loss = 0
        batches = 0
        model.eval()
        with torch.no_grad():
            for i, (x_batch, y_batch) in tqdm(
                enumerate(test_loader), total=len(test_loader), desc="Validation Round"):
                x_batch = x_batch.to(device)
                y_batch = y_batch.to(device)
                y_pred = model(x_batch)
                loss = loss_func(y_pred, y_batch.type(torch.int64))
                total_loss += loss.item()
                acc += (torch.argmax(y_pred, 1) == y_batch).float().sum().item()
#                 _, temp_pred = torch.max(output, 1)
#                 acc += torch.sum(temp_pred == labels.data).item()
                test_count += len(y_batch)
                batches = i + 1

        test_acc = (acc / test_count) * 100
        results['Test_accuracy'].append(test_acc)
        model.train()
        print(f'\n Corrupt: {corrupt}, Run: {run} Epoch: {epoch} Testing accuracy:{test_acc}, correct: {acc}, total:{test_count}')
        torch.save(model.to('cpu').state_dict(),
                       os.path.join(run_path,f'model_{epoch}.pth'))

        model.to(device)

        if train_acc >= 99.9:
            break
    temp_res_path = os.path.join(res_path,str(corrupt))
    os.makedirs(temp_res_path, exist_ok=True)
    df = pd.DataFrame(data=results)
    df.to_csv(os.path.join(temp_res_path,f"Run_{run}.csv"))

    del corrupted_train
